### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by HighFiv-e** [encounterplus/encounterplus#257] opened 2020-07-20 21:02 UTC
As a user, I would like to utilize keyboard shortcuts to open top and side toolbar navigation items.

**Comment by jacobjohnston** [comment] 2021-04-19 17:25
Proposed keyboard shortcuts are detailed in Issue #227

**Comment by Splinter714** [comment] 2021-05-26 03:09
Duplicate of #227 (consolidating)

**Closed by Splinter714** 2021-05-26 03:09 UTC
Labels: feature-request, ui
