### ISSUE TITLE
[Bug] Hostile/Neutral NPC light source and darkvision not visible, and both are locked in place when toggling from Friendly to Hostile/Neutral

### ISSUE THREAD

**Issue by Splinter714** [encounterplus/encounterplus#443] opened 2021-04-13 19:03 UTC
This is new since 4.11.1, I'm guessing related to fixing the shared visibility issue #410 . Two parts, but I'm fairly certain they're related. I can add screenshots later today if helpful, let me know.

1. Hostile/Neutral token "light sources" and "darkvision" aren't visible on iOS app at all, regardless of DM or Player view
    - both "light source" and "darkvision" should be visible in DM view
    - just "light source" should be visible in Player view, assuming line of sight and other factors aren't preventing it from being seen

2. If a token with "light source" and/or "darkvision" is changed from Friendly to Hostile/Neutral and the token is moved to see the change as @jurex mentioned in #410 , the light source remains visible and fixed in place while the token is Hostile/Neutral. This is regardless of token movement. This is not a problem when switching from Hostile/Neutral to Friendly.

**Comment by jurex** [comment] 2021-05-12 11:28
> both "light source" and "darkvision" should be visible in DM view

So this is not possible in the current LoS rendering engine, because it will reveal fog of war if enabled. There are multiple ways of showing enemy LoS, and I'm not sure which one I wanna use yet. It would be best to track this as a separate feature request. 

> just "light source" should be visible in Player view, assuming line of sight and other factors aren't preventing it from being seen

This is fixed now

> If a token with "light source" and/or "darkvision" is changed from Friendly to Hostile/Neutral and the token is moved to see the change as @jurex mentioned in #410 , the light source remains visible and fixed in place while the token is Hostile/Neutral. This is regardless of token movement. This is not a problem when switching from Hostile/Neutral to Friendly.

Got this fixed too, it was caused by disabled LoS calculation for all hostile tokens. You still need to move the token a bit to see the change or advance to next turn.

**Closed by jurex** 2021-05-12 11:28 UTC
Labels: bug, reviewed 4.11.1, vision
