### ISSUE TITLE
Allow Map Background Color To Be Chosen

### ISSUE THREAD

**Issue by dmmagic** [encounterplus/encounterplus#73] opened 2020-03-09 16:49 UTC
An option to change the map background color should be added. If I'm on the go and forgot to load in an ocean map, it would be great if I could change the background to blue. Or green for grass or brown for mountains, or whatever.

**Comment by Splinter714** [comment] 2021-04-14 03:15
Duplicate of #401

**Closed by Splinter714** 2021-04-14 03:15 UTC
Labels: enhancement, map
