### ISSUE TITLE
Feature Request: Allow delete of selected objects with the Delete/backspace key

### ISSUE THREAD

**Issue by Duseylicious** [encounterplus/encounterplus#136] opened 2020-04-18 20:13 UTC
Allow delete of select objects (both on map and in the Library) with the Delete/backspace key.  

On the Mac in particular, it would feel intuitive to be able to select something with the mouse and then press the delete key to remove it.

Bonus - (both on map and in the Library) allow Option-drag to duplicate.

**Comment by Taliesin1** [comment] 2021-05-24 20:23
See #227 for more keyboard ideas.

**Comment by Splinter714** [comment] 2021-05-26 03:07
Duplicate of #227 (consolidating)

**Closed by Splinter714** 2021-05-26 03:07 UTC
Labels: feature-request, input/hotkeys
