### ISSUE TITLE
Encounters Should Save Custom HP

### ISSUE THREAD

**Issue by dmmagic** [encounterplus/encounterplus#84] opened 2020-03-15 22:12 UTC
In an encounter I've created, I've manually increased the hit points of the monster beyond want the monster's normal hp would be. Then I save the encounter. When I reload the encounter, the hp did not save; instead, it's back to what is listed on the stat block. Is this a bug or intended behavior? I know I can create a new monster entry and change the hp and then use that monster, but I'd prefer not to fill up the Compendium with tons of monster duplicates.

**Comment by jurex** [comment] 2020-03-24 17:33
Right now it's intended behaviour. I'm storing only references to existing monsters, and their custom names. I don't want to add another values, unless it's really necessary. If there will be another request like this, I'll implement it.

**Comment by Duseylicious** [comment] 2020-04-13 06:05
I recently was hopping to be able to do what the request was.  

Example: An adventure says "This monster uses the stats of the a Bugbear, but has 70hp."  I'd like to setup the encounter ahead of time, without having to duplicate the monster for this one-off use.

**Comment by Duseylicious** [comment] 2020-07-02 16:44
I don't know if there is another ticket for this or not, but thinking about it I'd like this to take this a step further and be able to "save state" on an encounter.  Sometimes there are things added to a monster besides just HP, like a special attack.  It'd be great to be able to save every modification to the encounter, some how.

**Comment by Splinter714** [comment] 2021-04-18 22:56
Duplicate of #48

**Closed by Splinter714** 2021-04-18 22:56 UTC
Labels: enhancement
