### ISSUE TITLE
[Bug] Notifications for dice rolls may sometimes display the wrong dice roll.

### ISSUE THREAD

**Issue by Duseylicious** [encounterplus/encounterplus#314] opened 2020-09-29 18:04 UTC
Details here: https://discordapp.com/channels/565243968858751027/647438059226529807/760348224011108362

I caught one instance where a dice roll (pushed from EncounterBeyond) displayed the wrong dice roll - it displayed one of the previous rolls in the chat log instead.  
![Screen Shot 2020-09-29 at 10 50 23 AM](https://user-images.githubusercontent.com/63576494/94596910-af2ca300-0241-11eb-929e-6af26074bb87.png)
![Screen_Shot_2020-09-28_at_8 48 14_PM](https://user-images.githubusercontent.com/63576494/94598185-6ece2480-0243-11eb-8d8e-c8932ea7f1f4.png)

**Comment by Duseylicious** [comment] 2020-10-01 02:02
Just verified in a game with rrgeroge that it was not a one-off issue. :)

**Comment by rrgeorge** [comment] 2020-10-01 03:56
After a certain point in the game, the notifications were guaranteed to be incorrect. I couldn’t find any pattern to which notification would display, but they were always significantly older

**Comment by jurex** [comment] 2021-02-12 15:34
Hmmm, I cannot replicate this at all. It could be a bug in the previous version of realm database I'm using. Got a newer version installed, so let's see if this will be happening again.

**Comment by rrgeorge** [comment] 2021-02-12 15:36
It’s completely random and intermittent.

**Comment by jacobjohnston** [comment] 2021-04-15 16:57
We suspect this issue was caused by [this Realm issue](https://github.com/realm/realm-core/pull/4354) and using UUIDs for message IDs in E+. As of 4.11, E+'s version of Realm was updated to a version that includes a fix for this issue. A quick poll of people in Discord suggests that no one has seen the incorrect dice rolls crop up in E+, and thus, the issue is likely fixed. If anyone notices incorrect dice roll messages in the future, we should reopen this issue.

**Closed by jacobjohnston** 2021-04-15 16:57 UTC
Labels: bug - needs review, on hold
