### ISSUE TITLE
Pages Duplicating

### ISSUE THREAD

**Issue by dmmagic** [encounterplus/encounterplus#81] opened 2020-03-12 14:09 UTC
Something is causing pages to duplicate. From Tatonker in the Discord:

"I’ve had an issue the last couple of nights where pages that have been added as children of another page appear multiple times. It happens when I click the drop down / expand toggle, the pages will be duplicated. If I then close and open again they may be duplicated again showing a 3rd or even 4th copy. If I close the module and re-open everything looks fine, not use if it is a memory issue or something? I tried deleting one of the duplicates and it deleted the real version of the page which was no longer there when exiting the module and re-opening. Will see if I can recreate the exact steps tonight."

From me: "I've had the same issue, but I can never replicate it. But in my case, it's pages in a group."

MrWickedClown also reports this issue as happening to them.

**Comment by Splinter714** [comment] 2021-04-15 04:20
@dmmagic @MrWickedClown @tatonker anyone been able to reproduce this?

**Comment by Splinter714** [comment] 2021-04-16 20:06
Per discord discussion, hasn't been seen in a while, possibly since 4.9. Closing for now.

**Closed by Splinter714** 2021-04-16 20:06 UTC
Labels: bug - needs review, question
