### ISSUE TITLE
Search page contents as well as titles

### ISSUE THREAD

**Issue by ep1cman** [encounterplus/encounterplus#571] opened 2021-08-18 22:31 UTC
### What would you like to see added to EncounterPlus?
It would be great to have the option to also search the body text of pages with the search function. Some times I am trying to find information that is on a page but not in the title, e.g some NPC's details at a location

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.1): 
- Operating System (e.g. "iOS/iPadOS 14.2" or "macOS 11.3"):

**Comment by joelohrum** [comment] 2021-08-18 22:59
This is a duplicate of Issue 531.

**Closed** 2021-08-19 18:19 UTC
Labels: feature-request, library
