### ISSUE TITLE
Feature Request: Show external screen limits on DM view for better playability

### ISSUE THREAD

**Issue by maxlds** [encounterplus/encounterplus#275] opened 2020-07-30 21:08 UTC
When a DM is using the iPad as the primary screen and the players are using a secondary screen via HDMI/Airplay, sometimes it is difficult for the DM to know what the players are seeing since the aspect ratio from the iPad to the external screen may be different and the external screen could be landscape or portrait.  It's quite often that I have to look at the player screen to zoom and recenter to make sure I'm showing them what I intend to show them.

It'd be fantastic to show a box on my iPad that shows the borders of the TV screen that the players see so I can see what is on their screen. It would be nice if the DM could enable the overlay on the screen, choose the aspect ratio and have it synced with the landscape/portrait option for external screen.

See attached - red corners show extent of what external player screen sees.

![image0](https://user-images.githubusercontent.com/51212235/88974744-5909a680-d276-11ea-882b-d7da20b2155a.jpeg)

**Comment by Splinter714** [comment] 2021-04-29 23:20
Duplicate of #26

**Closed by Splinter714** 2021-04-29 23:20 UTC
Labels: feature-request
