### ISSUE TITLE
[Feature Request] Ability to add multiple characters at once to a campaign

### ISSUE THREAD

**Issue by lambersond** [encounterplus/encounterplus#207] opened 2020-06-12 01:29 UTC
Possibly add checkboxes to character list when adding them to a campaign so we can just have the add player window open once and done rather than once for every new character being added to a campaign.

**Comment by Splinter714** [comment] 2021-10-30 20:28
Duplicate of #130

**Closed by Splinter714** 2021-10-30 20:28 UTC
Labels: feature-request, compendium
