### ISSUE TITLE
"Show on external" ability for monsters / text

### ISSUE THREAD

**Issue by Rycochet** [encounterplus/encounterplus#32] opened 2020-02-12 23:07 UTC
Possibly linked to #30 too - but also needs to be able to store more information for monsters (like 5etools tabbed stat block, details, and image) - so that showing a monster to the players can be done on their screen, rather than having to pick up the MM etc

**Comment by Splinter714** [comment] 2021-04-18 22:39
Duplicate of #316

**Closed by Splinter714** 2021-04-18 22:39 UTC
Labels: enhancement
