### ISSUE TITLE
Dragging and Dropping Assets on macOS Doesn't Work

### ISSUE THREAD

**Issue by rrgeorge** [encounterplus/encounterplus#117] opened 2020-04-12 23:42 UTC
Couple of weird issues on macOS with dragging and dropping assets on macOS:
1. Dragging and dropping assets from the library creates a marker instead of dropping the asset
2. Dragging and dropping an asset (an image file) from the desktop drops the same picture no matter what, and then weird stuff. For example:
  a. Drag a.jpg and drop on map to put asset on map
  b. Drag b.jpg and drop on map to put asset on map, but another copy of a.jpg shows up
  c. Quit and reopen EncounterPlus, map now has 2 assets of b.jpg instead of two of a.jpg like before
  d. Drag c.jpg onto map, get another copy of b.jpg
  e. Quit and reopen EncounterPlus, all assets are now of c.jpg

**Comment by jurex** [comment] 2020-04-15 20:35
1. fixed
2. the issue is caused by empty suggested filename provided by macOS. Fixed by creating UUID filename as workaround to show images properly. I still need to investigate how to get the proper filename.

**Closed by jurex** 2020-04-15 20:35 UTC
Labels: bug, macOS
