### ISSUE TITLE
Impossible to drag & drop webp images on maps or in an asset pack

### ISSUE THREAD

**Issue by Tixuoty66** [encounterplus/encounterplus#399] opened 2021-03-15 18:44 UTC
On ipad, it's possible to import a webp image when creating an asset in a pack, but it's impossible to drag & drop multiple webp images in an asset pack, as it works with png files. It's also not possible to drag & drop a webp image from a directory to a map.

**Comment by Splinter714** [comment] 2021-04-25 22:34
Duplicate of #465

**Closed by Splinter714** 2021-04-25 22:34 UTC
Labels: feature-request, library
