### ISSUE TITLE
More robust and reliable, seamless iCloud integration

### ISSUE THREAD

**Issue by Taliesin1** [encounterplus/encounterplus#527] opened 2021-05-24 20:02 UTC
### What would you like to see added to EncounterPlus?
-Better iCloud integration, so I can move between machines easier without the hassle of exporting/AirDrop/importing. I fairly frequently have to switch between my iMac (where I do production and online sessions) and my MacbookPro (where I do all my VTT, in-person sessions)

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.1): 4.11.2
- Operating System (e.g. "iOS/iPadOS 14.2" or "macOS 11.3"): MacOS

**Comment by Splinter714** [comment] 2021-05-26 03:01
Duplicate of #525

**Closed by Splinter714** 2021-05-26 03:01 UTC
Labels: feature-request
