### ISSUE TITLE
Marker menu incomplete when single click on it

### ISSUE THREAD

**Issue by Tixuoty66** [encounterplus/encounterplus#467] opened 2021-04-24 07:41 UTC
### What went wrong?
- On a map, single click on a marker displays the following icons (edit, copy, delete, reference)

### What were you expecting to happen?
- Same menu than the one you get with right click / long press (edit, copy, delete, unhide, lock, reference). But, not sure it’s a bug, maybe it's better to have only the main options displayed as an icon on single click.

### What software versions are you currently using?
- EncounterPlus 4.11.1
- Operating System iPadOS 14.4.2

**Comment by Splinter714** [comment] 2021-04-24 17:10
I THINK this is by design. Will change to feature request, @jurex to confirm if it is indeed a bug.

**Comment by Tixuoty66** [comment] 2021-04-24 17:38
And if it’s by design, I suggest to close this issue.

**Comment by jurex** [comment] 2021-05-12 11:41
It's by design. The quick action menu should contain only most frequent actions, while context menu should contain all relevant actions. It seems like a duplicate functionality, but on iOS/iPad os, bringing long press action menu take some time to execute, so some might prefer just one more tap to display quick action. It's also easier to discover then long press. Closing for now.

**Closed by jurex** 2021-05-12 11:41 UTC
Labels: feature-request, invalid, markers, ui
