### ISSUE TITLE
Feature Request: Expanded (visible) text directly on map

### ISSUE THREAD

**Issue by Rycochet** [encounterplus/encounterplus#63] opened 2020-03-03 16:27 UTC
Would be nice to be able to show text directly on the map without needing to open a popup for it - though having the popup automatically visible would also work.

Use case is for "README" type info on a map for starter adventures, without needing to make it part of the map image itself.

**Comment by Splinter714** [comment] 2021-04-14 03:10
Duplicate of #412, closing here because easier to copy single comment to the newer issue.

**Closed by Splinter714** 2021-04-14 03:10 UTC
Labels: enhancement
