### ISSUE TITLE
Encounter Plus will not import file if launched from files

### ISSUE THREAD

**Issue by rrgeorge** [encounterplus/encounterplus#285] opened 2020-08-11 18:13 UTC
If EncounterPlus is not currently running, Launching it by opening a file with EncounterPlus does not import the file upon launch. Opening a file with EncounterPlus while it’s currently running will import the file as expected.

**Comment by jacobjohnston** [comment] 2021-04-15 17:05
There used to be a similar issue when opening from Finder on macOS, but that was resolved in 4.11. However, I can confirm this still seems to be an issue with Files on iOS.

**Comment by jurex** [comment] 2021-05-11 07:44
I've added proper url handler after cold start.

**Closed by jurex** 2021-05-11 07:44 UTC
Labels: bug, reviewed 4.11.1
