### ISSUE TITLE
Presented map must stay active for webclient

### ISSUE THREAD

**Issue by rrgeorge** [encounterplus/encounterplus#437] opened 2021-04-12 14:36 UTC
If the presented map is not the active tab in E+, then events from the webclient (such as movement or LoS updates) do not appear to work.

**Comment by Splinter714** [comment] 2021-04-14 02:52
@rrgeorge this appears to be a duplicate of #404, so I'm closing for tidiness. Please re-open if I'm missing something.

**Closed by Splinter714** 2021-04-14 02:52 UTC
Labels: enhancement, external-screen

**Comment by rrgeorge** [comment] 2021-04-14 02:54
Would you look at that! I missed that one when I searched for it. Good eye.
