### ISSUE TITLE
NSInternalInconsistencyException Crash 

### ISSUE THREAD

**Issue by sirkarm** [encounterplus/encounterplus#712] opened 2022-04-22 02:29 UTC
### What went wrong?
Application Specific Information:
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'It looks like you are calling a UIFocusDebugger method outside of lldb. That is not allowed.'
terminating with uncaught exception of type NSException
abort() called

### What were you expecting to happen?
Smooth crafting of my campaign.

### What steps can we follow to reproduce the issue?
I don't recall what I was doing exactly.

### What software versions are you currently using?
- EncounterPlus 4.15.1
- Operating System macOS 12.3.1 (21E258)

### Any screenshots, videos, logs, or error messages?
I've attached a crash log

### Any other comments?
[EncounterPlus.crash.txt](https://github.com/encounterplus/encounterplus/files/8536387/EncounterPlus.crash.txt)

**Comment by jurex** [comment] 2022-05-31 10:42
probably caused by #716, closing for now

**Closed as completed by jurex** 2022-05-31 10:42 UTC
Labels: bug
